# Generated by Django 4.2.3 on 2023-11-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_firstname_member_topic_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='topic_name',
            field=models.CharField(max_length=555),
        ),
    ]
