# Generated by Django 4.2.3 on 2023-11-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.CharField(default='Your default description here', max_length=1500),
        ),
    ]
