# Generated by Django 4.2.3 on 2023-11-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_member_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=555)),
                ('description', models.CharField(default='Your default description here', max_length=1500)),
            ],
        ),
    ]
