# Generated by Django 4.2.3 on 2023-11-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='description',
            field=models.CharField(default='Your default description here', max_length=1500),
        ),
    ]
